### ISSUE TITLE
DoExpressCheckoutPaymentRequestDetailsType requires public property $Version

### ISSUE THREAD

**Issue by xyph** [paypal/merchant-sdk-php#115]
\PayPal\EBLBaseComponents\DoExpressCheckoutPaymentRequestDetailsType requires, but doesn't have the public property $Version.

Without it, calling PayPal\Service\PayPalAPIInterfaceServiceService::DoExpressCheckoutPayment will throw Property PayPal\EBLBaseComponents\DoExpressCheckoutPaymentRequestDetailsType::$Version does not exist (/var/www/site/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPUtils.php:225)

Small stack trace

```
#0 /var/www/site/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPUtils.php(225): ReflectionProperty->__construct('PayPal\\EBLBaseC...', 'Version')
#1 /var/www/site/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPXmlMessage.php(30): PayPal\Core\PPUtils::propertyAnnotations(Object(PayPal\EBLBaseComponents\DoExpressCheckoutPaymentRequestDetailsType), 'Version')
#2 /var/www/site/vendor/paypal/merchant-sdk-php/lib/PayPal/PayPalAPI/DoExpressCheckoutPaymentReq.php(29): PayPal\Core\PPXmlMessage->toXMLString()
#3 /var/www/site/vendor/paypal/sdk-core-php/lib/PayPal/Formatter/PPSOAPFormatter.php(19): PayPal\PayPalAPI\DoExpressCheckoutPaymentReq->toXMLString()
#4 /var/www/site/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPAPIService.php(68): PayPal\Formatter\PPSOAPFormatter->toString(Object(PayPal\Core\PPRequest))
#5 /var/www/site/vendor/paypal/sdk-core-php/lib/PayPal/Core/PPBaseService.php(60): PayPal\Core\PPAPIService->makeRequest('DoExpressChecko...', Object(PayPal\Core\PPRequest))
#6 /var/www/site/vendor/paypal/merchant-sdk-php/lib/PayPal/Service/PayPalAPIInterfaceServiceService.php(502): PayPal\Core\PPBaseService->call('PayPalAPIAA', 'DoExpressChecko...', Object(PayPal\PayPalAPI\DoExpressCheckoutPaymentReq), Object(PayPal\Common\PPApiContext), Array)
```

To fix the issue, I've simply extended the class and used mine instead

```
class DoExpressCheckoutPaymentRequestDetailsType extends \PayPal\EBLBaseComponents\DoExpressCheckoutPaymentRequestDetailsType
{

    public $Version;

}
```

**Comment by jaypatel512** [comment]
Hey @xyph !

Thanks for helping us out there. Would you mind creating a tiny PR for this ? We love PRs 👍

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
